### ISSUE TITLE
Can Arduino nano 33 ble board use this library

### ISSUE THREAD

**Issue by yang66w** [arduino-libraries/Arduino_ScienceJournal#32]
Can Arduino nano 33 ble board use this library ，since I do not have Arduino nano 33 ble sense ？---https://github.com/arduino-libraries/Arduino_ScienceJournal

**Comment by per1234** [comment]
Hi @yang66w. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
